### ISSUE TITLE
Using server to create a 206 request

### ISSUE THREAD

**Issue by choonfahh** [Rob--W/cors-anywhere#124]
I created a CORS-anywhere on my own server and was wondering whether it's possible to manually create a 206 partial request through setHeaders? If it can be done, what headers should I add into the setHeaders option?

**Comment by Rob--W** [comment]
HTTP 206 is a partial response. That happens if the "Range" request header is set, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range and https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

Generally your proxy server should not take a non-range request from the client (e.g. web browser) and transform it into a range request, because the client won't expect such a 206 response.
