### ISSUE TITLE
Update response before sending

### ISSUE THREAD

**Issue by ArpanTanna** [Rob--W/cors-anywhere#126]
I want to remove all image tags and other changes from response.
Where can I update response before sending?
My assumption is in cors-anywhere.js file, but can't figure out exact location.

**Comment by Rob--W** [comment]
Transforming the response before sending is not supported.

If you want to, you can try it anyway as follows:

After this line,
https://github.com/Rob--W/cors-anywhere/blob/2ee31471ce3b624b5503bcc9c62fbe6783192c45/lib/cors-anywhere.js#L102
overwrite `proxyRes.pipe` with a custom function that intercepts the data, transforms it, and writes the result to `res`.

You should overwrite `proxyRes.pipe` because that will be called by the underlying library:
https://github.com/nodejitsu/node-http-proxy/blob/v1.11.1/lib/http-proxy/passes/web-incoming.js#L157

**Comment by ArpanTanna** [comment]
Thanks for quick reply!
But I haven't much information about pipe, better I can create one route and then call this function from that route.

Can you please let me know how can I add route?

**Comment by Rob--W** [comment]
`proxyRes` is an instance of [`http.IncomingMessage`](https://nodejs.org/api/http.html#http_class_http_incomingmessage), which is a readable stream (from where you can read the response to the proxied request).
`res` is an instance of [`http.ServerResponse`](https://nodejs.org/api/http.html#http_class_http_serverresponse), which is a writable stream (where you can write the response to the client).

When you replace `proxyRes.pipe`, you will be able to intercept responses on `proxyRes` via `data` events (and detect the end of stream via `end` events), which you can transform as desired, and when ready send the response to the client via `res.write`. See the linked documentation to learn more about interacting with readable and writable streams.
