### ISSUE TITLE
How can I change Cors Anywere requests headers for an external website?

### ISSUE THREAD

**Issue by robxxxx** [Rob--W/cors-anywhere#127]
I'm building website and part of it's main function is to open an external websitein a new tab and fill user name and password fields and then auto login for the users. Next, my web site should be able to listen on the external website's logout button, so that it can record if the user is still logged in or logged out.

As I'm doing the testing, I got to know that the browser same-origin-policy does not allow me get what I want. So I decided to use Cors Anywhere proxy to circumvent the same origin restriction. However, I still could not achieve what I want, because I get the errors shown in the screenshot . I thought altering the proxy http request headers would solve the problem. So I tried to change it in Cors Anywhere =>  server.js => setHeadher , but it does not seem to change it. Could you please help me? 
![test 1](https://user-images.githubusercontent.com/32246551/43549131-73d18de6-95fd-11e8-8410-3096357669c9.PNG)
![test 2](https://user-images.githubusercontent.com/32246551/43549138-78d4e176-95fd-11e8-9a85-2dd637403f74.PNG)
![test 3](https://user-images.githubusercontent.com/32246551/43549143-7d020120-95fd-11e8-8a7e-d0be6504e69c.PNG)

**Comment by Rob--W** [comment]
CORS Anywhere is not the right answer to your problem, because it is only meant for single requests and not a general web proxy. The errors in your image are caused by relative URLs that are resolved relative to the proxy's domain instead of the proxied domain. Furthermore, CORS Anywhere strips cookies to avoid accidentally leaking cookies meant for one site to another.

For your use case, start Chrome with a NEW profile and use the `--disable-web-security` flag to disable the same-origin policy. Do not use this profile for anything else besides testing, because this flag allows any website to send requests and run scripts on other websites.

Alternatively, create a browser extension to run scripts on other websites and/or perform cross-origin requests.

**Comment by robxxxx** [comment]
Hi Rob,

That was very informative. Thanks for your time. I did a further research and found out that probably "Electron" would solve my problem.

Let's see how it goes. Maybe, I would have to kill myself for another few days.

Anyway, I learned a lot while I was using your product. I was cool. Good Luck!
