### ISSUE TITLE
503 http error on live server

### ISSUE THREAD

**Issue by checho221** [Rob--W/cors-anywhere#155]
Hi, i am recently getting a 503 response from server, thanks in advance for fix it.

**Comment by DmitriyKylik** [comment]
Same issue. Prefixing target URL by https://cors-anywhere.herokuapp.com/    is not working. Thanks for fix!

**Comment by RuoyanMeng** [comment]
I got the same issue too, thanks in advance for fixing it!

**Comment by checho221** [comment]
@Rob--W , it is happening again, thanks for fixing it!

**Comment by Rob--W** [comment]
In the log files I see that the cause of those 503 errors is H12 (Request timeout; likely because there are too many users of the service.

A large number of requests appear to originate from radio/streaming sites. These types of sites have historically been a nuisance due to unreasonable resource usage (see #129). I've just identified another commercial library that is responsible for a huge chunk of requests, so I'm going to block them.

**Comment by checho221** [comment]
@Rob--W that is great, thankyou so much, pleas tell us when it is ready in order to make a test.

**Comment by Rob--W** [comment]
Blocking that specific library did not fix the issue. The server is receiving more requests than it can handle. Even when I lower the rate-limit to 6 requests per minute, the server is still unable to process all requests.

**Comment by checho221** [comment]
@Rob--W it sound like it is necesary a implement a load-balancer, i will be ready if you need help.

**Comment by Tatianisss** [comment]
Hi! Everything worked fine , but now comes the error "GET  https://cors-anywhere.herokuapp.com/URL 503 (Service Unavailable)"! How i can fix this? Just wait?

**Comment by benwille** [comment]
I'm getting the issue again. I'm wondering if this just happens from time to time and it will come back up or if there is something I need to report or fix on my end. I'm trying URL: https://cors-anywhere.herokuapp.com/http://www.nwslsoccer.com/stats?team=bn7w86uw8j61dga3xr5s0yiju&season=2019

**Comment by lisarutan** [comment]
Also having the same issue and the service seems to be down (visiting https://cors-anywhere.herokuapp.com/ returns an application error)...

**Comment by Rob--W** [comment]
When I view the log file, the error is `code=H11 desc="Backlog too deep"`

The server is overloaded, host your own one if availability is important. And see #301

**Comment by terrygreen0606** [comment]
I have hosted my own (cors-anywhere) in my heroku, but still getting 503 error.
Can you let me know how to fix?

**Comment by terrygreen0606** [comment]
Not sure why Cloudfare is related here, but it gives 503 Service Unavilable error with this preview image.
![image](https://user-images.githubusercontent.com/54503006/113580020-a9cc6d00-9657-11eb-8cd2-c7d9b925ae22.png)

**Comment by terrygreen0606** [comment]
https://github.com/Rob--W/cors-anywhere.git
Running this repository in localhost works perfectly as supposed as proxy to avoid cors error.
But if I host this on heroku, it returns the error above.
Any comments will be helpful.

**Comment by Rob--W** [comment]
@terrygreen0606 Your issue is unrelated to the issue reported here. If you still encounter issues, please file a new issue with a better description of the issue.

It seems that your issue is completely unrelated to CORS Anywhere though, and more related to your server configuration (using Cloudflare in the front, instead of letting Heroku manage all API calls).
