### ISSUE TITLE
CORS Anywhere demo doesn't work

### ISSUE THREAD

**Issue by SteveKm1** [Rob--W/cors-anywhere#168]
Hello,

I have downloaded the CORS-Anywhere demo.html and put it into my webserver root directory.

I see no any response in output windows after I try to "GET" anything(private or public). 
Anyways when I use curl on any public adress I see a response.

Is there any prerequsities to have CORS-Anywhere client side working? What kind of logs should I check if so?
For future I'd like to implement own CORS anywhere server, but I wanted to test first using the demo.

I can reach https://cors-anywhere.herokuapp.com/ from my webserver.

Thank you very much in advance.

**Comment by Rob--W** [comment]
demo.html itself doesn't provide any special functionality, and you should be able to use it from anywhere, including the root directory of your server. The most important part of demo.html is the URL at https://github.com/Rob--W/cors-anywhere/blob/4814647a9d21f14858da282387a4295c17f2851d/demo.html#L67

I just tried the demo and loaded `example.com`. It works flawlessly.

> Is there any prerequsities to have CORS-Anywhere client side working?

Documentation is available at https://cors-anywhere.herokuapp.com/

If you are not seeing any response at all, then it is more likely that the CORS Anywhere server that you are using is not reachable, e.g. because you used an invalid URL, or because you haven't started the server. If you used demo.html without modifications and still get not result, check whether you have blocked JavaScript or requests to the CORS Anywhere server in your web browser.

**Comment by SteveKm1** [comment]
I deployed the CORS-Anywhere server locally and used the demo, it works now partially(Not receiving output for external sites at all, just number 0). 

Not any modifications have been made to server, anyways, only access to internal backend is required for my purpose so current functionality is just okay.
Now I need to authorize my request by user and password(or Token), for that I will open another issue to have topic properly named. 
Thank you for your answer !
