### ISSUE TITLE
Alternative to cors anywhere! Make your own!

### ISSUE THREAD

**Issue by Zibri** [Rob--W/cors-anywhere#185]
Here you go!

https://github.com/Zibri/cf-cors-anywhere

Please do not use the demo link,
create a cloudflare account (it takes one minute) and upload the worker!

Thanks to @Rob--W for the inspiration.

**Comment by Rob--W** [comment]
Thanks for sharing. Since this does not have anything to do with CORS Anywhere, I'm going to close the issue though.

Note that `Access-Control-Allow-Credentials: true` does not work with a wildcard origin (at https://github.com/Zibri/cf-cors-anywhere/blob/2219411078fc4adb22a00dba8d9f7811e44e647a/index.js#L31). If you want to support credentials, an explicit origin must be set. Further, I don't understand why you're deleting `"X-Content-Type-Options`, as the header has no special behavior.

Another issue of your worker (compared to CORS Anywhere) is that you're buffering the full response before responding to the client. CORS Anywhere streams the response directly to the client, which does not only result in lower latency (good for the client), but also lower memory consumption (good for the operator of the CORS proxy server).

**Comment by Zibri** [comment]
@Rob--W 
Because without deleting it, chrome gives a warning (even if it works) deleting it the warning doesn't show.
About Access-Control-Allow-Credentials
what should I do?
You're welcome to contribute!
Clodflare is incredibly fast and multi-mirrored. 
You must try it.
Try the demo in the top of the page.
Tell me if I can improve it.

**Comment by Zibri** [comment]
Update code now exposes also received headers.

**Comment by Zibri** [comment]
Unfortunately it also adds cloudflare headers. It seems there is no way to avoid it.

```
Cf-Connecting-Ip: "xx.xx.xx.xx"
Cf-Ew-Via: "xx"
Cf-Ray: "4f861ebe4xxxxxx-YYY"
Cf-Visitor: "{"scheme":"https"}"
Cf-Worker: "cors.workers.dev"

```

**Comment by Zibri** [comment]
All fixed. Now cloudflare cors anywhere should work as intended.
https://github.com/Zibri/cloudflare-cors-anywhere
