### ISSUE TITLE
Q: Possible to use this with Google API? 

### ISSUE THREAD

**Issue by terryz21** [Rob--W/cors-anywhere#192]
I am trying to send the following POST request to Google Drive API

```
function uploadFn(file, token) {
    var metadata = {
        'name': 'Test File', // Filename at Google Drive
        'mimeType': file.type, // mimeType at Google Drive
    };

    var accessToken = token;
    var form = new FormData();
    form.append('metadata', new Blob([JSON.stringify(metadata)], {type: 'application/json'}));
    form.append('file', file);

    axios({
         method: 'put',
         url: 'https://cors-anywhere.herokuapp.com/https://www.googleapis.com/upload/drive/v3/files?uploadType=media',
         headers: {
              'Authorization': 'Bearer ' + accessToken,
         },
         data: form,
         responseType: 'json,
         withCredentials: true,
    })
   .then((response) => {
         console.log('success');
   })
   .then((error) => {
         console.log('failed');
   });

}
```

However, there a few errors I'm having trouble with. First, I read in the docs withCredentials cannot be true, but for APIs like Google Drive which require authentication through the request header, I must set withCredentials to true to allow the OAUTH process to succeed & if not, I get something like the following:

> Response to preflight request doesn't pass access control check: Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials. Origin .... is therefore not allowed access

Furthermore, CORS-Anywhere always returns a response header with header['Access-Control-Allow-Origin'] = '*'; However, both Chrome & FireFox will complain (not sure if its browser could also be the Google API) with the following error as well:

> Cannot use wildcard in Access-Control-Allow-Origin when credentials flag is true. 

Would this not be a valid use case to justify including something like setResponseHeader to allow devs to manipulate the response headers? I understand that this isn't safe practice, but in this case, I'm not actually going to deploy. Rather, I just want to test my client side. Is there any other way I can use this proxy to bypass CORS without actually having a real server ready? Apologize if this is kind of stupid, really new to web dev

**Comment by Rob--W** [comment]
When a custom `Authorization` header is used, you don't need `withCredentials` to forward credentials.

By design, `withCredentials` cannot be used with `Access-Control-Allow-Origin: *`. `withCredentials` means that any saved credentials are included with the request, whereas `Access-Control-Allow-Origin: *` means that any website can read the response. If a resource is public anyway, then no credentials are needed. So anyone who wants to include credentials in a response with a wildcard allowed origin is likely making a mistake.

And the Drive API already supports cross-origin requests. You don't need and should not use CORS Anywhere with Drive. For documentation, see https://developers.google.com/drive/api/v3/quickstart/js
