### ISSUE TITLE
What IP the target server sees?

### ISSUE THREAD

**Issue by Grobeu** [Rob--W/cors-anywhere#200]
My exact question is, if I use this proxy, does the target server sees that the calls originate for the user or from the proxy server?  (My concern is, in case the target server use rate-limiting mechanisms, will the calls passed through the cors-anywhere proxy be limited if too many users use the proxy to access a URL)

Thanks!

**Comment by Rob--W** [comment]
The target will obviously see the proxy server as the source IP.

The public CORS Anywhere demo also includes the client's IP in the `X-Forwarded-For` header, but any sane destination server will not use it for rate-limiting, as it is unwise to trust the value from third-party (proxy) servers (because its value can easily be spoofed).
