### ISSUE TITLE
404 Error: getaddrinfo ENOTFOUND https https: 80

### ISSUE THREAD

**Issue by ctwh** [Rob--W/cors-anywhere#201]
Hello,

I have Cors-anywhere hosted in a docker container on a server that receives traffic directed as a rewrite from another container running apache.  The apache container runs a web app, and upon being loaded in the browser, sends requests via a proxy to cors-anywhere like: 

https://<servername>/cors-anywhere/https://.../

A simple rewrite rule in the apache container directs traffic to the container running cors-anywhere: 

`RewriteRule "^/cors-anywhere/(.*)$" "http://${CORS_ANYWHERE_SERVER_HOST}:${CORS_ANYWHERE_SERVER_PORT}/$1" [P,NC,L]
`

When run locally, everything works fine.  However, when hitting the server,  I get this response:

`Not found because of proxy error: Error: getaddrinfo ENOTFOUND https https: 80
`

I am aware that an issue was raised with an identical error, but I don't know how to address it in apache.  Furthermore, I don't necessarily think the causes are the same either. 
[Possible related issue #167 ](https://github.com/Rob--W/cors-anywhere/issues/167 )

**Comment by Rob--W** [comment]
The issue is the same: You're using normalized URLs.
You should be looking for the raw values instead. I suppose that you can reconstruct the raw URL with `%{REQUEST_URI}` and `%{QUERY_STRING}` or even `%{THE_REQUEST}` (in `RewriteCond`) and then refer to the captured groups from the regexp with `%1`, `%2`, etc.

See the documentation at https://httpd.apache.org/docs/current/mod/mod_rewrite.html#RewriteCond

**Comment by ctwh** [comment]
Thank you, @Rob--W !

My solution:

`RewriteCond "%{REQUEST_URI}" "\/cors-anywhere\/https:\/(.*)"`
`RewriteRule "^/cors-anywhere/(.*)$" "http://${CORS_ANYWHERE_SERVER_HOST}:${CORS_ANYWHERE_SERVER_PORT}/https://%1" [P,NC,L]
`

Note above that `RewriteCond` still requires searching against a single slash (`https:/`) instead of (`https://`).  If you use `%{THE_REQUEST}` it will be a raw url (requiring you to search for `https://`).  The `%{REQUEST_URI}` I am using will also include query params for me.  

Furthermore, I was not able to stack RewriteCond lines and extract multiple capture groups for each line and having a reference to them (e.g. using %1 for a capture group for the first `RewriteCond`, %2 for the second `RewriteCond`).  That approach did not work, so my solution was driven by that limitation.

**Comment by a0309nkita** [comment]
Hi!

I'm working on angular project and from there I'm trying to post some logs to a server, but while hitting that server I got CORS error, and on searching I found that if I append https://cors-anywhere.herokuapp.com with my URL it'll work.

So after adding it my CORS error gone but now I'm getting proxy error like this:-  Not found because of proxy error: Error: getaddrinfo ENOTFOUND ****.****.com.

This is my code snippet
const response: any = await axios.post(LOGNESS_LOG_EVENT_URL, event, {
        headers: EVENT_HEADERS(bearer),
      });

and my LOGNESS_LOG_EVENT_URL is as :- https://cors-anywhere.herokuapp.com/https://********.

Please provide soln to this as I got stuck here.

**Comment by Androz2091** [comment]
Hello, I'm getting the same problem using Apache (the help page appears every time):
```
<VirtualHost *:443>

    ServerName cors-anywhere.androz2091.fr

    ProxyPass / http://localhost:3700/
    ProxyPassReverse / http://localhost:3700/

    LogLevel warn
    ErrorLog ${APACHE_LOG_DIR}/cors.androz2091.fr.log
    CustomLog ${APACHE_LOG_DIR}/cors.androz2091.fr.log combined

</VirtualHost>
```

What should I use?
