### ISSUE TITLE
Not able to make my videos working on another domain

### ISSUE THREAD

**Issue by Lalmi-Issam** [Rob--W/cors-anywhere#203]
Hello 
I have 2 dmoains domain1.com and domain2.com i want to stream video hosted in domain1.com that is requested by client in domain2.com
i used to set cookie with domiana.com but the cookie is not passed i tried to use this pakage but not working i tried i understand taht i need to 
1/ remove cookie from domain1.com (i don't want that)
2/ allow cookie from domain1.com to be set in domain2.com
the cookie is set by to protect videos against how want to download batch (counter many video is downloaded)

please help

**Comment by Rob--W** [comment]
Use custom headers instead of cookies.

**Comment by Lalmi-Issam** [comment]
i tried that before but it look like easy to be spoofed from client i found this article in stackoverflow do think it will work !?

[https://stackoverflow.com/questions/4701922/how-does-facebook-set-cross-domain-cookies-for-iframes-on-canvas-pages](url)

**Comment by Rob--W** [comment]
If the value of the expected request header is unpredictable and kept reasonably secure (e.g. locked behind authentication), then it should be fine to use it. The Authorization request header is often used for this purpose. Cookies and custom headers with API keys are alternatives.

I'm closing this issue since it is unrelated to my project.
