### ISSUE TITLE
Not found because of proxy error

### ISSUE THREAD

**Issue by voquochuyhuy** [Rob--W/cors-anywhere#204]
hello,
i got this error when fetching data from a web in live demo https://robwu.nl/cors-anywhere.html

GET https://gigamall.com.vn/vn/tin-tuc-su-kien/su-kien/
404 Not Found

Not found because of proxy error: Error: write EPROTO 140302471231360:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1922:

I also tried some urls like :https://vnexpress.net/ .It worked  and I don't know why the url above didn't work (https://gigamall.com.vn/vn/tin-tuc-su-kien/su-kien/)
Please help and sorry for my bad english

**Comment by Rob--W** [comment]
The destination server (`gigamall.com.vn`) only uses TLS 1.0, which is no longer supported. At the very least it must support TLS 1.2 to be meaningfully available over https. Its support for https is terrible: https://www.ssllabs.com/ssltest/analyze.html?d=gigamall.com.vn&hideResults=on

The server appears to also make its content available over http, so you could use http instead of https:

```
https://cors-anywhere.herokuapp.com/http://gigamall.com.vn/vn/tin-tuc-su-kien/su-kien/
```

**Comment by voquochuyhuy** [comment]
Thanks a lot
