### ISSUE TITLE
SSRF in CORS-Anywhere

### ISSUE THREAD

**Issue by rudSarkar** [Rob--W/cors-anywhere#215]
Hi Rob Wu,

## Short description
I found SSRF CORS-Anywhere.

## Request Header
```
GET /https://google.com HTTP/1.1
Host: cors-anywhere.herokuapp.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: https://html-color-codes.info
Connection: keep-alive
Referer: https://anysite.com
Pragma: no-cache
Cache-Control: no-cache
```

## PoC
![SSRF-1](https://serving.photos.photobox.com/62004758e8db38da84be6fbc36583a8e03d0dfcedb2b3824c20ad287f52b0334694b028c.jpg)

![SSRF-2](https://serving.photos.photobox.com/4487312946571a7083e1c79be8340883e277c6401acaa65c583f7820b61ae2d03c4a6085.jpg)

## Exploit
```
curl 'https://cors-anywhere.herokuapp.com/http://google.com' -H 'Connection: keep-alive' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36' -H 'Sec-Fetch-Dest: empty' -H 'Accept: */*' -H 'Origin: https://html-color-codes.info' -H 'Sec-Fetch-Site: cross-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://html-color-codes.info/colors-from-image/' -H 'Accept-Language: en-US,en;q=0.9,bn;q=0.8,hi;q=0.7,mt;q=0.6' --compressed
```

## Reference
https://hackerone.com/reports/115748

Thanks,
@rudSarkar

**Comment by Rob--W** [comment]
CORS Anywhere is basically an open proxy for http(s) (at least, the public demo is, and with some limitations). Being able to send requests to arbitrary URLs is a defining feature of this project, and as a result, this application should not be hosted on a network with untrusted clients (see https://github.com/Rob--W/cors-anywhere/issues/152#issuecomment-462187099 for some more details on security).

Since the CORS Anywhere demo is hosted externally, and offers access to public resources only, there is no SSRF vulnerability here.

**Comment by rudSarkar** [comment]
Thanks for your information. I was not sure and then I reported it! And thanks for fast response @Rob--W
