### ISSUE TITLE
The server receives an incorrect URL

### ISSUE THREAD

**Issue by ifyour** [Rob--W/cors-anywhere#228]
I deployed `cors-anywhere` on serverless, but I find that the URL is not working the way I expect it to, is there something wrong? Can you give some advice? Thank you.

Here is the source code: https://github.com/ifyour/icors

```js
module.exports = (req, res) => {
  const [_url] = Object.keys(req.query);
  req.url = `/${_url || ''}`;
  cors_proxy.emit('request', req, res);
};
```

Try it 👉🏻 https://icors.now.sh/?https://httpbin.org/anything

![image](https://user-images.githubusercontent.com/15377484/79943488-96061600-849b-11ea-8d44-b9acd90f99d2.png)

**Comment by Rob--W** [comment]
You copied the full code from my library to your repository, and it is not obvious whether you have made any other changes. Could you add `cors-anywhere` as a dependency to your package.json and let me know if it works? In case you didn't know: `lib/cors-anywhere.js` is the entry point when used as a library.

FYI, I get the expected result when I use `https://httpbin.org/anything` with the CORS Anywhere demo (at https://robwu.nl/cors-anywhere.html).

**Comment by ifyour** [comment]
> Could you add cors-anywhere as a dependency to your package.json and let me know if it works?

Of course, I deployed a version again where I used the original package and, [it seems](https://icors.now.sh/?https://httpbin.org/anything) still didn't work the way expected. 

Could it be that this `emit` method is the problem? I'm guessing. Thank you for your reply.

**Comment by Rob--W** [comment]
httpbin looks at the `X-Forwarded-For` request header, and uses it instead of the `Host` header if it is set.

Because you haven't set the `xfwd` option, the underlying http-proxy library assigns those headers, and that's why you are observing this difference.

Unrelated but still important: Your example lacks the recommended `requireHeader` and `removeHeader` configurations. This is a significant security risk, and you should add those at least.

For the default configuration in the demo, see:
https://github.com/Rob--W/cors-anywhere/blob/4814647a9d21f14858da282387a4295c17f2851d/server.js#L23-L41

By the way, this is a terrible way of parsing the URL: `const [_url] = Object.keys(req.query);`.
It will cut off anything after `=` or `&`. Use better fitting string functions instead.

**Comment by ifyour** [comment]
> By the way, this is a terrible way of parsing the URL: const [_url] = Object.keys(req.query);.
It will cut off anything after = or &. Use better fitting string functions instead.

Thanks for the answer. I fixed the problem.


> httpbin looks at the X-Forwarded-For request header, and uses it instead of the Host header if it is set.
Because you haven't set the xfwd option, the underlying http-proxy library assigns those headers, and that's why you are observing this difference.

How do I configure it if I want to get the same results? 

```js
{
  ...
  httpProxyOptions: {
    xfwd: true
  }
  ...
}
```
