### ISSUE TITLE
redirect_uri in OAuth request causing a 401

### ISSUE THREAD

**Issue by afc75** [Rob--W/cors-anywhere#232]
Hi

We're looking to use this to resolve CORS issues when sending OAuth requests to an ADFS server, however when passing the GET request to the proxy for the authorization code, the proxy returns a "401 not authorized".  Other requests are fine so wondering if this is a limitation.

The request we are sending is:

https://adfs.ourdomain.com/adfs/oauth2/authorize?response_type=code&client_id=cecc8f3e-e700-48a6-b3e7-89ad3d2f1986&resource=cecc8f3e-e700-48a6-b3e7-89ad3d2f1986&redirect_uri=http://ourapplicationserver/something

Sending the the following returns a 200 however obviously doesn't give us what we need as we need to be able to pass the redirect_uri parameter

https://adfs.ourdomain.com/adfs/oauth2/authorize?response_type=code&client_id=cecc8f3e-e700-48a6-b3e7-89ad3d2f1986&resource=cecc8f3e-e700-48a6-b3e7-89ad3d2f1986

This is a local cors-anywhere installation

**Comment by Rob--W** [comment]
This is not an issue with CORS or CORS Anywhere. You should check whether your expectations of the different components in your system are correct. This includes checking whether any of the servers rely on client-specific state (such as cookies, or sessions bound to specific IP addresses or user agents).

Note that CORS Anywhere is a proxy that doesn't transfer cookies by design, because there is no secure or reliable way to relay cookies.
