### ISSUE TITLE
Adding the protocol to the URL causes the help page to appear

### ISSUE THREAD

**Issue by AgentJay** [Rob--W/cors-anywhere#238]
Hello,

Thanks for this! I am plagued by cors issues all the time.

So it's handy to be able to specify the protocol since I would like to have mixed content (http and https) being delivered to my https page.

While adding the protocol in your demo seems to work great I'm having issues.

These are the 2 tests that I'm hoping will eventually both work:
https://proxy.biopama.org/www.google.com (works)
https://proxy.biopama.org/https://www.google.com (gives the help page)

**Comment by Rob--W** [comment]
This is an issue of your server configuration. You apparently have another server in front of the CORS Anywhere proxy, which normalizes the URL.

In 0.4.1 and before, the proxy would attempt to connect to the invalid host, and end up with errors like `Not found because of proxy error: Error: getaddrinfo ENOTFOUND` (e.g. #167 and many other reported issues on this issue tracker). In #239, you mentioned the use of Apache. See #201 for instructions on properly configuring Apache to direct requests to CORS Anywhere.

As of 0.4.2, the URL validation is more strict, and invalid URLs are mapped to the homepage instead of an error page.

Since this is a common error and a very frequently asked question from people who try to self-host CORS Anywhere, I should probably consider catching the special case and show a specialized error page instead...

**Comment by Rob--W** [comment]
I changed the code to spit out a more descriptive error message when this happens.
