### ISSUE TITLE
Using api key as an environment variable in cors proxy.

### ISSUE THREAD

**Issue by dsaw** [Rob--W/cors-anywhere#259]
I have been using this wonderful proxy setup to take care of requests for a web application. It uses an api service which requires keys. Now, setting it on the client code is a no-no as it would be exposed there. So, the most convenient way was to just put in an `.env` file and refer to it by `process.env.REACT_APP_VAR` (using CRA). 
However, you can see the key while making the request so a better way would be to set on the proxy itself. 
i.e. Receive the `https://cors-proxy-serv.herokuapp.com/https://website1.com/app=1` request, append the key as a query parameter on the proxy itself and forward it.
Is this a good method or is there any better/robust way?

Thank you for this project.

**Comment by Rob--W** [comment]
It's only reasonable IF all of the following conditions are true:

- The proxy is allowed to know the key (because it needs to know about the key in order to set it).
- All destination servers are allowed to see the key (in particular, a client should not be able to set a custom URL from where they can intercept the key).
- The key should not be added to URLs from redirects (because CORS Anywhere [adds the response URLs in the response header for debugging purposes](https://github.com/Rob--W/cors-anywhere/blob/a0309e6c475036b4ba2a04372f8d5b6462bd4825/lib/cors-anywhere.js#L186-L187)). If you do want to use this with redirects, disable internal redirect handling by setting `maxRedirects: 0` in the construction of the server.

URLs are often logged somewhere (e.g. in access logs). If possible, I suggest to pass the API key via a request header instead.
