### ISSUE TITLE
How to alter or inject param into request?

### ISSUE THREAD

**Issue by cory-weiner** [Rob--W/cors-anywhere#269]
I'm using cors anywhere to serve as a reverse proxy server for API access which requires a client_secret key. I'd like to have the proxy server inject this client secret into the request parameters.

I see there is a function for setHeaders. Can I suggest the addition of a setParams configuration which would allow the addition or modification of parameters on the source request.

**Comment by cory-weiner** [comment]
I've added a pull request to add this functionality:
https://github.com/Rob--W/cors-anywhere/pull/270

**Comment by Rob--W** [comment]
Rewriting the requested URL is outside of the scope of this project. As a library consumer, you can easily achieve the desired result with a custom server in front of it, as explained at https://github.com/Rob--W/cors-anywhere/issues/81#issuecomment-327133851 .

Even with `setParams`, the parameters are not hidden because the requested URL is reflected in the `x-final-url` response header: https://github.com/Rob--W/cors-anywhere/blob/a0309e6c475036b4ba2a04372f8d5b6462bd4825/lib/cors-anywhere.js#L217

Even if that response header were not to be set, then you would need to be very careful to not inadvertently leak the secret, i.e. ensure that the parameters are only appended to the URL if the URL is an exact match for the destination server. Otherwise anyone can trivially create a request to leak the "secret" parameter (to an external server).
