### ISSUE TITLE
Fetch request assistance please

### ISSUE THREAD

**Issue by Dave-Lindberg** [Rob--W/cors-anywhere#292]
I've set up a couple successful REST requests via a private version of cors-anywhere, using Insomnia, and then use the generated code in a simple React app. 

The GET request works fine, but my POST request produces a 400 error: 
```
Code: "MissingRequiredFields"
Message: "The following parameters are required: Username, Password" 
```

The generated code looks like this: 

```
fetch("https://a-private-cors-anywhere.herokuapp.com/https://api.mindbodyonline.com/public/v6/usertoken/issue", {
  "method": "POST",
  "headers": {
    "content-type": "application/json",
    "api-key": "12345",
    "siteid": "67890",
    "user-agent": "uvac-welcome-screen,uvac-welcome-screen",
    "x-requested-with": "XMLHttpRequest"
  },
  "body": {
    "Username": "_DaveLindberg",
    "Password": "some-password"
  }
})
.then(response => {
  console.log(response);
})
.catch(err => {
  console.error(err);
});
```

Any insights on what's missing would be greatly appreciated!

**Comment by Rob--W** [comment]
`body` cannot be a plain object. The server receives `[object Object]` when you do that.

For the accepted values, see https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Body

Since you're passing `Content-Type: application/json` as the request header, I think that you meant to submit a JSON-formatted request body. Turn the object into a string before doing so with `JSON.stringify` (there is an example earlier in the page that I linked).
