### ISSUE TITLE
CORS Drop

### ISSUE THREAD

**Issue by mjamie** [Rob--W/cors-anywhere#299]
There CORS link dropped for sometime today. I'm not sure if this is a regular occurrence or whether something happened today. I usually use the prefix link for google drive links in unity to play videos.

Just wondering if anything did happen or maybe there is an issue.

Thanks.

**Comment by Rob--W** [comment]
... regularly playing videos is not the kind of intended use case for the public demo server. The drop could be due to server downtime or due to you hitting the rate-limit.

You should either self-host CORS Anywhere, or preferably look for a way to achieve the desired functionality without a proxy server. It's not scalable.
