### ISSUE TITLE
Application Error on open

### ISSUE THREAD

**Issue by jarridlima** [Rob--W/cors-anywhere#300]
Hi, I'm trying to access the page https://cors-anywhere.herokuapp.com/ and the following error are showing:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

Can you help me how can I solve it?

![image](https://user-images.githubusercontent.com/8194683/101946606-ecac9580-3bcd-11eb-9c1e-e414561fa81a.png)

**Comment by Rob--W** [comment]
I wasn't watching logs, and the application is up again. Last time something like this happened, it was due to the large number of users with unreasonable usage patterns. I'll take measures in #301 to improve this. If you want to use CORS Anywhere for anything that requires a good availability, self-host CORS Anywhere.
