### ISSUE TITLE
getaddrinfo ENOTFOUND When Hosting in Azure

### ISSUE THREAD

**Issue by afc75** [Rob--W/cors-anywhere#305]
Similar issue to a few previous issues however I'm getting a "getaddrinfo ENOTFOUND" error when hosting CORS-Anywhere in Azure as a web service.  I've looked at the previous solutions where another server sits in front of CORS-Anywhere but these aren't options in Azure as Microsoft maintain the Docker instance.  Just wondering if you have any ideas on this?  If not, my other option is to build a full Linux VM in Azure to host CORS-Anywhere.

Thanks

**Comment by Rob--W** [comment]
Are you using the latest version of CORS Anywhere? In earlier versions this error could show up if CORS Anywhere was sitting behind a front that mangled/normalized the URL (e.g. `//` -> `/`). In the latest version it is still not supported (but the generic help page is shown instead). If this is the case, you should try to look for a way to disable URL rewriting (so that the URL sent by the client is not altered). If that is not possible, then you can try to omit `/https://` or `/http://` (and use `/`) instead; CORS Anywhere will then automatically prepend `http://` (or `https://` if you add `:443` to the URL).

If you're using the latest version of CORS Anywhere, and are still experiencing `getaddrinfo ENOTFOUND`, then it could be that DNS is not properly configured on your server (which prevents any application, including CORS Anywhere, from resolving host names to IP addresses). To check if this is the case, you could input a public IP, e.g. `https://[location of your proxy instance]/https://1.1.1.1` and check the response.

I'm not familiar with Azure specifically, but if you post more details here others may be able to help out.

**Comment by afc75** [comment]
Apologies, meant to close this off last year.  The latest version of CORS-Anywhere resolved this.
