### ISSUE TITLE
Wildcard origin not allowed - error while submitting AMP form

### ISSUE THREAD

**Issue by anuragphadke** [Rob--W/cors-anywhere#307]
We have a URL at https://shivaami.webfast.app/hangouts-meet-hardware-kit.html and I am trying to submit the "We're here to help you" form.

On the backend, I am using CORS-Anywhere with AMP-Redirect-To header to redirect on successful form completion.
I get a 200 on my server, but on the browser its a CORS error
"WildcardOriginNotAllowed"

What specific setting should I be using here?

Complete curl below:

curl 'https://webfast-proxy.ngrok.io/https://www.shivaami.com/submit_form.php?form=hangouts-meet-hardware-kit&__amp_source_origin=https%3A%2F%2Fshivaami.webfast.app' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: application/json' \
  -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryZGR7BTRWywTB8dyY' \
  -H 'Origin: https://shivaami.webfast.app' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://shivaami.webfast.app/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --data-raw $'------WebKitFormBoundaryZGR7BTRWywTB8dyY\r\nContent-Disposition: form-data; name="name"\r\n\r\nAnurag Phadke\r\n------WebKitFormBoundaryZGR7BTRWywTB8dyY\r\nContent-Disposition: form-data; name="email"\r\n\r\nanurag@webfast.co\r\n------WebKitFormBoundaryZGR7BTRWywTB8dyY\r\nContent-Disposition: form-data; name="phone"\r\n\r\n2135090575\r\n------WebKitFormBoundaryZGR7BTRWywTB8dyY\r\nContent-Disposition: form-data; name="website"\r\n\r\n\r\n------WebKitFormBoundaryZGR7BTRWywTB8dyY--\r\n' \
  --compressed

**Comment by Rob--W** [comment]
I suspect that you're trying to make a request with credentials (`credentials: "include"` with fetch, `xhr.withCredentials = true` with XMLHttpRequest). If that is used, the browser requires the server to respond with the value of the `Origin` request header instead of `access-control-allow-origin: *`.

You should try to configure the client to not include credentials.

If that is not possible, you could consider changing this to return `request.headers.origin || '*'` instead of `'*'`: https://github.com/Rob--W/cors-anywhere/blob/528ad7109fa55bdde8055dd035bb16140a29c336/lib/cors-anywhere.js#L54

PS. your configuration of CORS Anywhere is insecure. You have dropped the `Origin` / `X-Requested-With` requirement from the config, which means that the server can be used as a generic web proxy (i.e. anyone can open the URL in the browser and the response shows up). CORS Anywhere is NOT designed for use as a generic web proxy, you should enforce validation of the Origin request header.
