### ISSUE TITLE
Does cors-anywhere support forwarding web sockets?

### ISSUE THREAD

**Issue by sofusskovgaard** [Rob--W/cors-anywhere#328]
Hello!

Does cors-anywhere support forwarding web sockets?

I couldn't find anything that confirms that it does or doesn't support them.

**Comment by Rob--W** [comment]
It does not. In order to handle WebSocket requests, you would have to fork the library and add an "upgrade" event listener to the server, and forward that to the desired destination.

- `server` is created here: https://github.com/Rob--W/cors-anywhere/blob/9f1af8243463ab71b63b889fff5606bd908f36cc/lib/cors-anywhere.js#L420-L426
- documentation for `upgrade` event: https://nodejs.org/api/http.html#http_event_upgrade
