### ISSUE TITLE
My code not working with same error

### ISSUE THREAD

**Issue by fahd78** [Rob--W/cors-anywhere#336]
window.addEventListener("load", () => {
  let long;
  let lat;
  let temperatureDescription = document.querySelector(
    ".temperature-description"
  );
  let temperatureDegree = document.querySelector(".temperature-degree");
  let locationTimezone = document.querySelector(".location-timezone");

  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition((position) => {
      long = position.coords.longitude;
      lat = position.coords.latitude;

      const proxy = "https://cors-anywhere.herokuapp.com/";
      const api = `${proxy}https://weathersync101.herokuapp.com/weather/${lat},${long}`;

      fetch(api)
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          const { temperature, summary } = data.currently;
          temperatureDegree.textContent = temperature;
        });
    });
  }
});

**Comment by Rob--W** [comment]
Have you seen the pinned announcement? That may be the cause.

It seems that you're requesting data from an app on Heroku that you've developed yourself. If you own the backend, it is far better to send the CORS response headers yourself (e.g. `Access-Control-Allow-Origin: *`) instead of using a CORS proxy.
