### ISSUE TITLE
Help With Inegration?

### ISSUE THREAD

**Issue by kreativeteksolutions** [Rob--W/cors-anywhere#370]
So I installed node.js on my apache server hosted by GoDaddy and I have successfully installed CORS Anywhere to a subfolder in one of the directories. I did all this via SSH but no matter what I do I cannot seem to get a response from the directory I installed CORS Anywhere on. I have spent 5-6 hours trying to figure out what I am doing wrong but still no vail. Any help or guidance would be helpful. When I visit the page it opens the template that describes what cors anywhere does but if I make a fetch request I get the content of the page rather than the data being fetched.

**Comment by Rob--W** [comment]
There is not enough detail here to help you. How do you "make a fetch request"?

At this point it is not clear whether you have (1) actually have a successful installation of CORS Anywhere, and (2) whether you are performing a cross-origin request.

Your remark "I get the content of the page rather than the data being fetched." implies that your web page can read the response, but that's possibly just the source code instead of an invocation of the Node.js server script.

**Comment by kreativeteksolutions** [comment]
> There is not enough detail here to help you. How do you "make a fetch request"?
> 
> At this point it is not clear whether you have (1) actually have a successful installation of CORS Anywhere, and (2) whether you are performing a cross-origin request.
> 
> Your remark "I get the content of the page rather than the data being fetched." implies that your web page can read the response, but that's possibly just the source code instead of an invocation of the Node.js server script.

Sorry I forgot to close this issue. I ended up figuring it out. Thank you!
