### ISSUE TITLE
How to skip a specially file (a file not through the proxy)

### ISSUE THREAD

**Issue by titanco** [Rob--W/cors-anywhere#43]
Hello,
I have a file on server like: "crossdomain.xml" and how i can access it via url:
http://host:port/crossdomain.xml

**Comment by Rob--W** [comment]
How are you using CORS Anywhere?

**Comment by titanco** [comment]
I'm using CORS Anywhere for a flash video player, and flash player request 'crossdomain.xml' on root of domain.
I try put crossdomain.xml on my serve but when i access via http://host:port/crossdomain.xml it show 404 error.
So, can i do that with CORS Anywhere ? Where i can put 'crossdomain.xml' file ?

**Comment by titanco** [comment]
I just hack to your code and add:
`if (location.host === 'crossdomain.xml') {
      res.writeHead(200, {'Content-Type': 'application/xml'});
      var xmll = '';
      res.end(xmll);
      return;
    }`
But this is not legit, can you have any idea?

**Comment by Rob--W** [comment]
You can simply create a CORS Anywhere server without listening on a port, and then create another HTTP server that handles requests to /crossdomain.xml and otherwise forwards the request to CORS Anywhere.

For example:

```javascript
var cors_proxy = require('cors-anywhere');
cors_proxy.createServer({
  requireHeader: ['origin', 'x-requested-with'],
  removeHeaders: [
    'cookie',
    'cookie2',
  ],
  // See README.md for other options
});

var fs = require('fs');
require('http').createServer(function(req, res) {
  if (req.url === '/crossdomain.xml') {
    fs.createReadStream('crossdomain.xml').pipe(res);
    return;
  }
  // Let the server handle it
  cors_proxy.emit('request', req, res);
}).listen(8080); // Listen on port 8080.
```

Reading the file again on every acces of crossdomain.xml is not quite efficient, I recommend reading the caching the contents of the file if possible.

Also note that the above code handles `http://example.com:8080/crossdomain.xml` but not `http://example.com:8080/crossdomain.xml?some=value` because it looks for an exact match. If you want to allow any prefix to be handled, use `req.url.startsWith('/crossdomain.xml')` instead (modern Node.js versions only) or `req.url.lastIndexOf('/crossdomain.xml', 0) === 0` (any Node.js version).

**Comment by titanco** [comment]
Thank you so much for your time !
Closing ...

**Comment by titanco** [comment]
Hello,
I try your code, but it show error:
`TypeError: cors_proxy.emit is not a function`

**Comment by Rob--W** [comment]
I've edited the snippet, and changed

```javascript
var cors_proxy = require('cors-anywhere');
cors_proxy.createServer(...);
```

to

```javascript
var cors_proxy = require('cors-anywhere').createServer(...);
```

**Comment by titanco** [comment]
Its woking, thank you.
