### ISSUE TITLE
Is it possible for this to display different HTML depending on whether or not the user is on mobile?

### ISSUE THREAD

**Issue by Dgameman1** [Rob--W/cors-anywhere#44]
I'm testing a quick website, and I'm not sure what the issue is but I believe that the HTML that is returned depends on whether or not the website provides the same HTML as the mobile version.

Or does this ignore the dimensions of the user using it?

**Comment by Rob--W** [comment]
That sounds more like an issue with the site that you're trying to proxy than an issue with CORS Anywhere. CORS Anywhere does not modify the request other than the bare minimum to get cross-domain requests to work in a safe way.

**Comment by Dgameman1** [comment]
Well, When I use this on for example stackoverflow, I get different HTML depending on whether or not I'm doing this on a mobile device.

https://www.diffchecker.com/y8p9ji2g

The one on the left is for Desktop, and the one on the right is on Mobile

**Comment by Rob--W** [comment]
It seems that they may be doing user-agent sniffing and serving a different response depending on the value of the User-Agent header.

You could host your own instance of CORS Anywhere and use `setHeaders` to set your own custom header.

See https://github.com/Rob--W/cors-anywhere#server for documentation and https://github.com/Rob--W/cors-anywhere/blob/f07bdc4ea0982c98e7ca2bbad4766407c360664c/test/test.js#L717-L746 for tests.

**Comment by Dgameman1** [comment]
Is there zero way of just adding setHeaders to 
```
	$.ajaxPrefilter(function(options) {
		if (options.crossDomain && jQuery.support.cors) {
			var http = (window.location.protocol === 'http:' ? 'http:' : 'https:');
			options.url = http + '//cors-anywhere.herokuapp.com/' + options.url;
		}
	});

```

Or anything? I'm on shared hosting and it would just make my life easier if it were possible to do it this way without having to host anything

**Comment by Rob--W** [comment]
Although the latest version of the `fetch` specification allows clients to set the `User-Agent` header (https://fetch.spec.whatwg.org/#forbidden-header-name), previous versions of the XHR spec did not (https://www.w3.org/TR/2014/WD-XMLHttpRequest-20140130/#dom-xmlhttprequest-setrequestheader). Firefox supports overriding User-Agent from the client since version 43 (https://bugzil.la/1188932), but Chrome does not (https://crbug.com/571722).

So, if you are fine with this working in some browsers only, just set the User-Agent header from the client. Otherwise host your own version of CORS Anywhere.

The README links to Heroku, you could get your own version of CORS Anywhere up and running in just a few minutes (it shouldn't take more than an hour).

If you are unfamiliar with Node.js, the easiest thing to get started is to fork my repository, edit server.js and add `setHeaders: {'User-Agent': ' ... some non-mobile user agent here ...'}` and push the repo to Heroku. If you are familiar with Node.js, I recommend adding `cors-anywhere` as a dependency, copy `server.js` and tweak it to your needs.

**Comment by Dgameman1** [comment]
I honestly' don't know much about the server end side of things. I followed you up until the push repo to Heroku part, but I'll just figure that out.

Thanks!

**Comment by kevinchau321** [comment]
Does safari for iOS support overriding User-Agent? I tried adding `setHeaders` to `cors_proxy.createServer` in `server.js` but I'm still running into this issue viewing on mobile.

**Comment by Rob--W** [comment]
> Does safari for iOS support overriding User-Agent? I tried adding setHeaders

CORS Anywhere runs on the server, so it does not matter whether the client is iOS or something else.
