### ISSUE TITLE
live radio use case: Missing required request header. Must specify one of: origin,x-requested-with

### ISSUE THREAD

**Issue by narshingbari** [Rob--W/cors-anywhere#481]
Dear respected sir please help me 
Actually i am trying to use http live radio url in my https website .
I don't know who made this site https://www.liveradio.es/
its working fine like https://www.liveradio.es/http://202.144.155.12/radio1

But i deployed cors-anywhere on Render https://cors-anywhere-kzu4.onrender.com/ 
by watching this tutorial video : https://www.youtube.com/watch?v=5SvCeHyKxus
not woking https://cors-anywhere-kzu4.onrender.com/http://202.144.155.12/radio1
but it not working getting this message : Missing required request header. Must specify one of: origin,x-requested-with

please anyone help me 
![Screenshot 2024-03-29 081552](https://github.com/Rob--W/cors-anywhere/assets/33945951/5dd6542f-4dc5-4636-a879-b7f35c8ea210)

**Comment by Rob--W** [comment]
Opening the URL directly in the browser results in `Missing required request header. Must specify one of: origin,x-requested-with` because such a request is different from when the web application uses `fetch`, `XMLHttpRequest` or any other API. The "error" on its own does not provide any useful information for debugging your web application, and you should use your browser's developer tools to see the actual requests / responses.

On to your specific problem:
A web application with radio usually has two subresource request types:
- initial request for metadata, which may reference other metadata or the URL of the stream.
  For example, a URL with the .m3u8 file extension.
- further requests for the media itself. For example, .mp3 / .ogg files.

For the radio to work smoothly, you need to make sure that you are prepending your CORS Anywhere server URL before all requests.

I'm going to close this issue, since it is not a problem with CORS Anywhere.

**Comment by narshingbari** [comment]
Dear sir i already emailed you at _rob@robwu.nl_
Could you please help me to do that i will pay you sir, i need this

**Comment by Rob--W** [comment]
Your email does not contain anything that isn't already here.

In my previous reply (above) I've already explained the likely cause of your issue. Implement what I am suggesting in your web app and your issue will probably disappear. This is not an issue with CORS Anywhere.

**Comment by narshingbari** [comment]
Dear sir i dont have too much knowledge for it 
actually this site made by your project its working https://www.liveradio.es/
then why not working my one
could you please guide me properly 🙏
