### ISSUE TITLE
Multiple Links in the same server

### ISSUE THREAD

**Issue by darkrole** [Rob--W/cors-anywhere#53]
is that possible to use multiple links in the same server? 
id like to use "domain02, domain03" etc in the same server!
is that possible?
check my code below and u will know what im talking about.

```
// Heroku defines the environment variable PORT, and requires the binding address to be 0.0.0.0
var host = process.env.PORT ? '0.0.0.0' : '0.0.0.0';
var port = process.env.PORT || 8090;

var originBlacklist = parseEnvList(process.env.CORSANYWHERE_BLACKLIST);
var originWhitelist = parseEnvList(process.env.CORSANYWHERE_WHITELIST);
function parseEnvList(env) {
  if (!env) {
    return [];
  }
  return env.split(',');
}

var cors_proxy = require('lib/cors-anywhere').createServer({
  originBlacklist: originBlacklist,
  originWhitelist: ['http://mydomain.com'],
  requireHeader: ['origin', 'x-requested-with'],
  removeHeaders: [
    'cookie',
    'cookie2',
  ],
  // See README.md for other options
});

var fs = require('fs');
require('http').createServer(function(req, res) {
  req.url = req.url.replace(/^\/domain01(\/|$)/, '/http://realsource.com');
  // Let the server handle it
  cors_proxy.emit('request', req, res);
}).listen(8090); // Listen on port 8090.
```

**Comment by Rob--W** [comment]
I don't mind helping, but please learn some JavaScript before opening new issues again. Your opened issues (#48, #49, #51) depicts someone who is just getting started with server-side JavaScript. The responses to #51 indicate that you are not very familiar with JavaScript.

Although I can easily offer an aswer to your question above, I believe that it's better that you learn the language that you're programming in, so that you can solve your own problems yourself instead of having to depend on others to create programs. There are many online resources for learning, e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide

Hint: Copy and paste the line containing `.replace`, and modify the parameters (to get domain2, domain3, etc.). This requires the domains to not overlap (one domain starting with another), which is most likely true because the pattern shows that the domain must either end with nothing (`$`), or a slash.

**Comment by darkrole** [comment]
ok mate!
Thank you!
