### ISSUE TITLE
Hide origin source

### ISSUE THREAD

**Issue by darkrole** [Rob--W/cors-anywhere#68]
is there a way to hide the original source using the pipe function or something?
i mean if u use firebug or google inspector u can still find the original source, is there a way to hide it 100%?
really need it, thanks

this is my code: 
`var originBlacklist = parseEnvList(process.env.CORSANYWHERE_BLACKLIST);
var originWhitelist = parseEnvList(process.env.CORSANYWHERE_WHITELIST);
function parseEnvList(env) {
  if (!env) {
    return [];
  }
  return env.split(',');
}

var cors_proxy = require('./lib/cors-anywhere').createServer({
  originBlacklist: originBlacklist,
  originWhitelist: ['http://mysite.com', 'http://mysite2.com'],	
requireHeader: ['origin', 'x-requested-with'],
  removeHeaders: [
    'cookie',
    'cookie2',
  ],
  // See README.md for other options
});

var fs = require('fs');
require('http').createServer(function(req, res) {
  req.url = req.url.replace(/^\/channel1(\/|$)/, '/https://channel1.com/live/$1');

  
  // Let the server handle it
  cors_proxy.emit('request', req, res);
}).listen(8080); // Listen on port 8080.

id like to hide this source: https://channel1.com/live/

**Comment by Rob--W** [comment]
Do you mean the `x-request-url`, `X-CORS-Redirect` and the `x-final-url` headers? You could fork the repo and remove the lines in `lib/cors-anywhere.js` that set these headers. However, there is usually little point in doing so since often the original source is already leaked in numerous other ways (in the original response of the original server).

**Comment by darkrole** [comment]
yes i mean it! 
so its impossible to totally hide the original source?

**Comment by Rob--W** [comment]
I currently have no plans to try and add source-hiding functionality to the proxy. You can follow my suggestions from my previous comment if you want to.

**Comment by darkrole** [comment]
come on mate, help me haha
i already did what u suggest, it works!
thanks

**Comment by darkrole** [comment]
my goal is hide my original source because using ur proxy, it blocks 100% the other people to use my stream, it really works only on my website, and the original source its failing doing that

**Comment by Rob--W** [comment]
If you can control the original stream, a better solution is to check the value of the "Origin" request header at your server and if it is not your website's origin, drop the request.

**Comment by darkrole** [comment]
yes, i block it on my original stream, but if someone use a proxy like yours they can use my stream in other wbsites, using ur proxy on my stream i can block them all, so im using ur proxy to protect my stream

**Comment by Rob--W** [comment]
> yes, i block it on my original stream, but if someone use a proxy like yours they can use my stream in other wbsites, using ur proxy on my stream i can block them all, so im using ur proxy to protect my stream

This is something that you cannot really defend against. The effectiveness of my proxy is based on clients (browsers) that respect the HTTP protocol. If you assume that adversaries can generate arbitrary requests (a proxy server is capable of generating any request), then they can also send a request to your server and forge headers to trick your proxy server into passing through the request.

(I'm closing this issue because there is no actionable task for me).
