### ISSUE TITLE
Should CORS be abandoned?

### ISSUE THREAD

**Issue by jackzhp** [Rob--W/cors-anywhere#86]
I think that CORS design is completely unnecessary, stupid, and so should be abandoned. I have laid down my arguments, if you think you know this issue pretty well, would you please look at it, and comment it.

https://github.com/jackzhp/CORS-should-retire
or
http://blog.sina.com.cn/s/blog_93b70ae70102wxe8.html

Hope you can contribute to the change!

**Comment by Rob--W** [comment]
Closing ticket since it does not have anything to do with the project.

I have no desire to engage in a discussion with you about this topic, so I'll just drop my feedback here.

> But no one really gets to the substantial point: the simple Adobe’s approach I proposed brings what extra security issues. I would say none. If you think there is any, please enlighten me!

In short: web servers are not prepared to authenticate cross-origin requests. For example, consider an internal wiki on an intranet. The resource is currently protected by the same-origin policy that prevents it from being read by other websites. With your proposal, the resource could easily leak to unauthorized web pages.

---

Longer version:
In your proposal you basically shift the responsibility of managing access control from the owner of the resource to the requester of the resource. Furthermore, to compensate for the loss of the default restrictive access control policy, you assert that the resource owners should enforce access control by e.g. not replying with content if the request fails to pass validation.

This latter assertion is unrealistic, because the security (secrecy of resources) of the web platform relies on the same-origin policy, where websites are isolated by origin. If you default to allowing resources to be read across origins, then (all) websites that rely on the current security guarantees will be vulnerable to information leakage.

**Comment by jackzhp** [comment]
At first, really appreciate for the respond.

>In short: web servers are not prepared to authenticate cross-origin requests. 
>For example, consider an internal wiki on an intranet. 
>The resource is currently protected by the same-origin policy that prevents
> it from being read by other websites. 
>With your proposal, the resource could easily leak to unauthorized web pages.
Yes. you are right, the site has to make some changes: do referrer based authentication check either with http header referrer or header Origin. If the site does not do this authorization check, then you are right.

>Longer version:
>In your proposal you basically shift the responsibility of managing access control
> from the owner of the resource to the requester of the resource. 
This is completely opposite. what I proposed is to have the access control (authorization based on referrer) completely done by the owner of the resource, should not get browsers involved except for Referrer/Origin header.

At present, with CORS the authorization check (imposing access control) is done mainly by browsers or at least we say to get browsers heavily involved. What I meant(my proposal) is that no web server should delegate referrer based authorization check from their web server to browsers. 

>Furthermore, to compensate for the loss of the default restrictive access control policy, 
>you assert that the resource owners should enforce access control 
>by e.g. not replying with content if the request fails to pass validation.
Yes, if a request can not pass the referrer based authorization check is trying to hack the site.
I guess we have the same understanding here.
http://1st.com/a.html wants load http://2nd.com/someSecreteData.
At the server of 2nd.com, it checks the referrer/Origin of the request, if the refer is authorized(partner site or different site but owned by same owner) then serve, if this is not authorized(not a partner site), then reject.

>This latter assertion is unrealistic, because the security (secrecy of resources) of the web platform
> relies on the same-origin policy, where websites are isolated by origin. 
With my proposal, I still need "this same origin policy", but not same site policy, need the sandbox structure at browser side. For http://1st.com/ to deem http://2nd.com/ as same origin does not imply http://2nd.com/ to deem http://1st.com as same origin. They are still in different sandbox, can not interfere others freely.

>If you default to allowing resources to be read across origins, then (all) websites
>that rely on the current security guarantees will be vulnerable to information leakage.
You are right. If the servers do not do referrer(domain/origin) based authorization check at server side.
What I object is to have browsers heavily got involved in the referrer based authorization check.
Web servers should not delegate this authorization check to remote browsers.

Thank you for discussion. I would suggest when you mean "same site policy", please do not use the term "same origin policy".
