### ISSUE TITLE
Heroku App seems to be down

### ISSUE THREAD

**Issue by tomcek112** [Rob--W/cors-anywhere#90]
Hi,

https://cors-anywhere.herokuapp.com/ seems to be down (again). Is this something people are working on or should I switch to another service?

**Comment by Rob--W** [comment]
It was down because of a crash, I can't find any stack trace.

It seems up again, but sometimes requests are still slow: log fishow error
code H11 (Backlog too deep). I briefly looked at the logs and already see
many rate-limited (denied) requests within a few minutes... 124k
rate-limited requests in just 100 seconds (and 10k accepted requests).
Somehow my API is very popular among radio streaming sites.

**Comment by tomcek112** [comment]
Thanks for the fix, seems to be working again.
