### ISSUE TITLE
Feature Request: Enable Caching options

### ISSUE THREAD

**Issue by meehanman** [Rob--W/cors-anywhere#93]
It would be great to provide the feature/example of using caching to cache requests used through the proxy.

**Comment by Rob--W** [comment]
Caching responses is outside the scope of this project.
The public demo server is already approaching its boundaries with the current load alone, adding a disk cache or memory cache will likely increase the stress on the server. Moreover, since there are no constraints on the requests, I cannot tell whether a response can or should be cached.

Nothing stops you from adding a caching layer in front of the proxy though. There are multiple ways to do it, e.g. in front of the application (e.g. with Varnish) or before handing off the request to CORS Anywhere (e.g. by using CORS Anywhere as an internal request handler in Node.js, and servicing requests from a cache (memory/disk) and otherwise fall back to sending a request through CORS Anywhere (and storing the response in a cache)).
