### ISSUE TITLE
Why does CORS doesn't works while testing localhost

### ISSUE THREAD

**Issue by nkkel** [Rob--W/cors-anywhere#97]
Hey, 
Let's say my web application is running locally at 127.0.0.1:8080 and my API is at 127.0.0.1:3000 ... When i use $.get with 127.0.0.1:3000 from the console opened on webpage at 127.0.0.1:8080 , It says 
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:3000/login. (Reason: CORS header 'Access-Control-Allow-Origin' missing).```

That's fine because :3000 is different from :8080 hence failed. So I tried to use your cors-anywhere.com  like
```
$.get("http://cors-anywhere.herokuapp.com/http://127.0.0.1:3000", function(data) {
    alert(data);
});
```

It says, 404 Not Found xhr and `Missing required request header. Must specify one of: origin,x-requested-with`

Question is : 
1.) Why does that fails?
2.) How can I fetch the content of localhost:3000 from localhost:8000 while testing locally ??

**Comment by Rob--W** [comment]
To answer 1), let's first restate what you said:

> Let's say my web application is running locally at 127.0.0.1:8080
> and my API is at 127.0.0.1:3000 ...
> When i use $.get with 127.0.0.1:3000 
> from the console opened on webpage at 127.0.0.1:8080 , 

So, you are sending a request from `:8080` to `:8080` (a request to proxy the API at `:3000`).
This is clearly a same-origin request, there is no need to use a CORS proxy since you are already able to send a request to the server without CORS.

For 2: You can send a direct request, `$.get("http://127.0.0.1:3000", ...);` without an intermediate proxy.
If you really want to proxy anyway, ensure that the request is cross-origin, e.g. by using `http://localhost:8080` instead of `http://127.0.0.1:8080`.
